### ISSUE TITLE
Disallow devs from using whitespace for indentation in Ruby files

### ISSUE THREAD

**Issue by yedhink** [bigbinary/wheel#557]
@rishabhanand12 _a

Please take this up.

You can add the following rule under [this section](https://github.com/bigbinary/wheel/blob/1f84ef093f55552b20395077492e0fcf473f2758/.rubocop.yml#L410-L412).

```yaml
# Remove extra/unnecessary whitespace which's used for alignment.
# A developer shouldn't waste time indenting code with whitespaces.
Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false
```
